---
title: Klimawahl
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
paginate: 5
markdown: kramdown
highlighter: rouge
permalink: none
plugins:
- jekyll-paginate
- jekyll-sitemap
