title:  klimawahl
tagline: klimawahl ist eine Arena für Klimapolitik-Ansätze. Wir identifizieren Knackpunkte zwischen Wissenschaft, Politik, Wirtschaft und Zivilgesellschaft | klimawahl wird gemacht von einer unabhängigen Gruppe von Forschern und Journalisten. 
author: 
  name:  klimawahl
#  twitter:  paululele

# Change to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# google-ID: 'UA-80213386-1'

menu:
- {name: 'Über uns', url: 'about.html'}
#- {name: 'Writing', url: 'writing.html'}
#- {name: 'Contact', url: 'contact.html'}

social:
# - {icon: 'github', link: 'https://www.github.com/lenpaul'}
- {icon: 'twitter', link: 'https://twitter.com/klimawahl'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'facebook', link: 'http://www.facebook.com/klimawahl/'}
- {icon: 'envelope', link: 'mailto:info@klimawahl2017.de'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
 
